title: Zendesk Attachment Storage Offload 
tagline: "Offload Zendesk attachments into external storage, saving up to 90% on costs."
author: "eh7p"
logo: "/assets/images/logo.png"
description: > # this means to ignore newlines until "show_excerpts:"
  Store old attachments externally to Zendesk 90% cheaper.
  Retain full access within Zendesk via the sidebar app. 
baseurl: "/zd-offload"
url: https://eh7p.com # change this URL, this is needed for generating right sitemap

permalink: "/blog/:title/"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

css_dir: "assets/css" # defaults to "css"

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/img/logo.png

highlighter: rouge

collections:
  posts:
    output: true
    permalink: "/blog/:title"
  pages:
    output: true
    permalink: "/:title"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - .gitignore
  - vendor
